### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by panqian1222** [karimmamer/WheatRustClassification#1]
Hello, I want to make sure that you are sure this program can run through?
I found numerous bugs during the debugging process and felt that the program was not viable

**Comment by karimmamer** [comment]
Hi, I used this code in the competition and it should work.
Can you be more specific about the bugs you are facing?

**Comment by panqian1222** [comment]
> Hi, I used this code in the competition and it should work.
> Can you be more specific about the bugs you are facing?

Ok.I'm sorry I didn't clarify my questions.I solved some problems, but I didn't solve this one.
1. The following problems occur in generate_library_of_models.py:
 RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.
        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:
            if __name__ == '__main__':
                freeze_support()
                ...
        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe

I've tried to change this, I guess because my computer runs on Windows, but I've found a solution that doesn't solve the problem.
2. I would like to know your accuracy rate.I am very interested in the network model you used, so I want to study it.
Finally, Thank you for reading my questions and replies, thank you very much.

**Comment by karimmamer** [comment]
My apologies for the late reply. 
I tested my code on Ubuntu only so I won't be able to help you in the mean time.
Regarding the performance, I used it to achieve the fourth place in "ICLR Workshop Challenge #1: CGIAR Computer Vision for Crop Disease" with log loss of 0.21. you can find the leaderboard here: https://zindi.africa/competitions/iclr-workshop-challenge-1-cgiar-computer-vision-for-crop-disease/leaderboard

**Comment by panqian1222** [comment]
> 我对迟到的答复表示歉意。
> 我仅在Ubuntu上测试了我的代码，因此在此期间我将无法为您提供帮助。
> 关于性能，我用它在对数损失为0.21的“ ICLR研讨会挑战[＃1](https://github.com/karimmamer/WheatRustClassification/issues/1)：CGIAR作物疾病的计算机视觉”中排名第四。您可以在此处找到排行榜：[https](https://zindi.africa/competitions/iclr-workshop-challenge-1-cgiar-computer-vision-for-crop-disease/leaderboard) : [//zindi.africa/competitions/iclr-workshop-challenge-1-cgiar-computer-vision-for-crop-disease/leaderboard](https://zindi.africa/competitions/iclr-workshop-challenge-1-cgiar-computer-vision-for-crop-disease/leaderboard)

**Comment by panqian1222** [comment]
Ok, thank you for your reply.
Now I have run your program successfully.
I saw in a comment section that you shared your network model and other information with everyone through a video. I would like to know whether the video was kept or not.

**Comment by karimmamer** [comment]
I made a presentation about my solution at the ICLR 2020 Workshop on Computer Vision for Agriculture. You can find all workshop presentations here: https://www.cv4gc.org/cv4a2020/
